TESTS_ENVIRONMENT += \
 TIMEOUT="$(TIMEOUT)" \
 MKTEMP="$(MKTEMP)"

check_PROGRAMS +=

TESTS += \
 tests/basic.sh

EXTRA_DIST += \
 tests/basic.sh \
 tests/mochi-quintain-provider.json\
 tests/quintain-benchmark-example.json

DISTCLEANFILES += \
    test-output.gz \
    quintain.ssg
